# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailserver', '0001_initial'),
        ('emailuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailuser.EmailUser'),
        ),
        migrations.AddField(
            model_name='emailelementmapping',
            name='email_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.EmailElement'),
        ),
        migrations.AddField(
            model_name='emailelementmapping',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailuser.EmailUser'),
        ),
        migrations.AddField(
            model_name='emailelement',
            name='email_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emailserver.EmailThread'),
        ),
        migrations.AddField(
            model_name='emailelement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailuser.EmailUser'),
        ),
    ]
